version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: bbp
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    binary: bbp

release:
  prerelease: "auto"
  mode: "append"

changelog:
  groups:
    - title: 'New Features'
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: 'Documentation updates'
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 2
    - title: 'Other'
      order: 999
